/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mig_remoid_MainActivity */

#ifndef _Included_com_mig_remoid_MainActivity
#define _Included_com_mig_remoid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mig_remoid_MainActivity_DIMENSION
#define com_mig_remoid_MainActivity_DIMENSION 4096L
#undef com_mig_remoid_MainActivity_HALF_DIMENSION
#define com_mig_remoid_MainActivity_HALF_DIMENSION 2048L
/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    openInputDevice
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mig_remoid_MainActivity_openInputDevice
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    openInputDeviceWithoutPermission
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mig_remoid_MainActivity_openInputDeviceWithoutPermission
  (JNIEnv *, jobject);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    closeInputDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_closeInputDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    closeInputDeviceWithoutRevertPermission
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_closeInputDeviceWithoutRevertPermission
  (JNIEnv *, jobject);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    keyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_keyDown
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    keyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_keyUp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    keyStroke
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_keyStroke
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    touchDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_touchDown
  (JNIEnv *, jobject);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    touchUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_touchUp
  (JNIEnv *, jobject);

/*
 * Class:     com_mig_remoid_MainActivity
 * Method:    touchSetPtr
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mig_remoid_MainActivity_touchSetPtr
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
